#!/usr/bin/env python
import argparse
import datetime
import io
import zipfile
from itertools import islice
from pathlib import Path

import requests


class Logger:
    start: bool
    filename: Path

    def __init__(self, folder: Path):
        now = datetime.datetime.now()
        self.filename = (
            folder
            / f"log~{now.year}-{now.month}-{now.day}T{now.hour}-{now.minute}-{now.second}.txt"
        )
        self.start = False

    def log(self, msg: str):
        if not self.start:
            return
        with open(self.filename, "a", encoding="utf-8") as logfile:
            logfile.write(msg)


def main(
    mscz_files_csv: Path,
    download_folder: Path,
    overwrite: bool,
    ids: list[str] = None,
    n: int = None,
):
    i = 0
    logger = Logger(download_folder)
    with open(mscz_files_csv, "r") as mscz_file:
        for line in islice(mscz_file, 1, None):
            id, ref, path = line.split(",")
            if (download_folder / f"{id}.zip").exists():
                if not overwrite:
                    logger.log(f"{id} skipped (not overwrite)\n")
                    continue
                if ids and id not in ids:
                    logger.log(f"{id} skipped (not specified)\n")
                    continue
            ipns = ref[6:]
            url = f"https://ipfs.infura.io/ipfs/{ipns}/"
            res = requests.get(url)
            if res.status_code != 200:
                # log failed requests
                logger.log(f"{id} skipped {res.status_code}\n")
                continue
            # Read ZipFile to check contents
            try:
                zf = zipfile.ZipFile(io.BytesIO(res.content))
            except zipfile.BadZipfile:
                logger.log(f"{id} skipped {res.status_code} BadZipfile\n")
                continue
            if not list(filter(lambda n: n.endswith(".mscx"), zf.namelist())):
                logger.log(f"{id} skipped {res.status_code} {zf.namelist()}\n")
                continue
            # Save whole ZipFile
            with open(download_folder / f"{id}.zip", "wb") as outfile:
                outfile.write(res.content)
                logger.start = True
                logger.log(f"{id} updated {res.status_code} {zf.namelist()}\n")
                i += 1
            if i == n:
                break


REPO = Path(__file__).resolve().parent.parent.parent
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Download musescore files from IPFS links."
    )
    parser.add_argument(
        "--links",
        nargs=1,
        type=str,
        default=(REPO / "assets/mscz-files.csv").__str__(),
        help="path to mscz-files.csv (default: ~/assets/mscz-files.csv)",
    )
    parser.add_argument(
        "--folder",
        nargs="?",
        type=str,
        default=(REPO / "assets/musescore").__str__(),
        help="folder to place downloaded musescore files (default: ~/assets/musescore)",
    )
    parser.add_argument(
        "--overwrite",
        nargs="?",
        type=bool,
        const=True,
        default=False,
        help="overwrite specified ids (default: skip)",
    )
    parser.add_argument("ids", nargs="*", type=str, help="specific ids to overwrite")
    parser.add_argument(
        "-n",
        nargs="?",
        type=int,
        default=10,
        help="number of files to download or overwrite (default: 10)",
    )

    args = parser.parse_args()
    print(args)
    main(
        mscz_files_csv=Path(args.links),
        download_folder=Path(args.folder),
        overwrite=args.overwrite,
        ids=args.ids,
        n=max(args.n, len(args.ids)),
    )
    print("done!")
